spring:
  profiles: dev

master:
  datasource:
      url: jdbc:mysql://10.10.196.7:3306/focus_broker?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: dev#pass
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1

slave:
  datasource:
      url: jdbc:mysql://10.10.196.7:3306/focus_broker?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: dev#pass
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1